---
- name: "[WORDPRESS] - update cache"
  apt:
    update_cache: yes
  become: yes

- name: "[WORDPRESS] - Install LAMP"
  apt:
    name: ['apache2', 'php','php-mysql', 'mariadb-server', 'php-common', 'libapache2-mod-php', 'python-mysqldb', 'wget']
    state: present
  become: yes

- name: "[WORDPRESS] - start apache2 && mariadb"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  with_items:
    - apache2
    - mariadb

