---
- name: "[WORDPRESS] - update cache"
  apt:
    update_cache: yes
  become: yes

- name: "[WORDPRESS] - Install LAMP"
  apt:
    name: "{{ package_name }}" 
    state: present
  become: yes

- name: "[WORDPRESS] - start apache2 && mariadb"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  with_items:
    - apache2
    - mariadb

